name: Upload Release Assets

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: get latest ci id
      id: get_ci_id
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        # get all runs of the ci workflow
        json=$(gh api repos/${{ github.repository }}/actions/workflows/ci.yml/runs)

        # find first run that is github sha and status is completed
        id=$(echo $json | jq '.workflow_runs[] | select(.head_sha == ${{ github.sha }} and .status == "completed") | .id' | head -n 1)
        if [ ! "$id" ]
        then
          echo "No completed runs found"
          echo "ci_id=0" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        echo "ci_id=$id" >> "$GITHUB_OUTPUT"

    - name: get latest ci artifacts
      if: steps.get_ci_id.outputs.ci_id != 0
      uses: actions/download-artifact@v4
      env:
        GH_TOKEN: ${{ github.token }}
      with:
        merge-multiple: true
        run-id: ${{ steps.get_ci_id.outputs.ci_id }}
        github-token: ${{ github.token }}

    - run: |
        ls

    - name: upload release assets
      if: steps.get_ci_id.outputs.ci_id != 0
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release upload ${{ github.event.release.tag_name }} "./aarch64-unknown-linux-musl.deb" \
          --clobber \
          --repo="${{github.repository}}"
        gh release upload ${{ github.event.release.tag_name }} "./aarch64-unknown-linux-musl-debug.deb" \
          --clobber \
          --repo="${{github.repository}}"
        gh release upload ${{ github.event.release.tag_name }} "./x86_64-unknown-linux-musl.deb" \
          --clobber \
          --repo="${{github.repository}}"
        gh release upload ${{ github.event.release.tag_name }} "./x86_64-unknown-linux-musl-debug.deb" \
          --clobber \
          --repo="${{github.repository}}"
        gh release upload ${{ github.event.release.tag_name }} "./oci-image-aarch64-unknown-linux-musl.tar.gz" \
          --clobber \
          --repo="${{github.repository}}"
        gh release upload ${{ github.event.release.tag_name }} "./oci-image-aarch64-unknown-linux-musl-debug.tar.gz" \
          --clobber \
          --repo="${{github.repository}}"
        gh release upload ${{ github.event.release.tag_name }} "./oci-image-x86_64-unknown-linux-musl.tar.gz" \
          --clobber \
          --repo="${{github.repository}}"
        gh release upload ${{ github.event.release.tag_name }} "./oci-image-x86_64-unknown-linux-musl-debug.tar.gz" \
          --clobber \
          --repo="${{github.repository}}"
        gh release upload ${{ github.event.release.tag_name }} "./static-aarch64-unknown-linux-musl" \
          --clobber \
          --repo="${{github.repository}}"
        gh release upload ${{ github.event.release.tag_name }} "./static-aarch64-unknown-linux-musl-debug" \
          --clobber \
          --repo="${{github.repository}}"
        gh release upload ${{ github.event.release.tag_name }} "./static-x86_64-unknown-linux-musl" \
          --clobber \
          --repo="${{github.repository}}"
        gh release upload ${{ github.event.release.tag_name }} "./static-x86_64-unknown-linux-musl-debug" \
          --clobber \
          --repo="${{github.repository}}"
